/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health/": {
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/users/": {
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
    post: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/users/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
}

export interface definitions {}

export interface operations {}

export interface external {}
